/*
    try {
        
    } catch (e) {
        console.error(e); // first will show error, then continue the code.
        console.log("hello")// show the hello message
    }   

    You received an error with try catch, but even with the error the app will continue to running


    try {
        
    } catch (e) {
        throw new error // break the app
        console.log("hello") // it wont show anything because the app chrashed
    } 

    
*/